### PR TITLE
Dashboard: Transpiler

### PR DESCRIPTION
**Pull request by tbohlen**
Creates a build pipeline for our html/css/js dashboard code. This will let us write our js in multiple separate files to keep it clean.

### CODE REVIEW

**Comment by tbohlen** [comment]
Hey @KenwoodFox want me to just approve and merge? Or some other action? Wondering what to do now that it is assigned to me!

**Comment by KenwoodFox** [comment]
> Hey @KenwoodFox want me to just approve and merge? Or some other action? Wondering what to do now that it is assigned to me!

I tried testing this out and had a few issues getting it to run, also id like to see if the transpiled code works and is portable on the nuc before merging, we should try that out today :3 when will you be in person next @tbohlen ?

**Comment by tbohlen** [comment]
I'll be here today from 3 to 5:30!

**Comment by KenwoodFox** [comment]
Yay!

**Comment by KenwoodFox** [comment]
@tbohlen did you commit back the changes made yesterday?

**Comment by tbohlen** [comment]
Just pushed!

**Review by KenwoodFox — APPROVED** [review]
I like it, better than google.com

**Pull request merged**
